name: My action

on:
  workflow_dispatch:
    inputs:
      trigger_id:
        description: 'Trigger ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Trigger ID
      run: |
        echo "Trigger ID: $TRIGGER_ID"
      env:
        TRIGGER_ID: ${{ github.event.inputs.logLevel }}

    - name: Sleep
      run: |
        echo 'Hello, world!'
        echo 'Sleep...'
        sleep 1m
        echo '... awake again!'
