name: My action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Sleep
      run: |
        echo 'Hello, world!'
        echo 'Sleep...'
        sleep 1m
        echo '... awake again!'
